Create UI for profile page
rhdevs/rhapp pull request #4
Opened 2020-12-14 16:06 UTC by Licheng-Wu

Currently have minimal functionality, still trying to understand Typescript

2020-12-14 16:32 UTC, cjunxiang commented
thanks for the effort! will look through very soon

2020-12-15 03:43 UTC, cjunxiang commented on frontend/src/routes/Routes.tsx
> +  PROFILE_PAGE = '/profile',
existing conflict with main-branch. Resolve it before merging!

2020-12-15 03:43 UTC, cjunxiang commented on frontend/src/routes/Profile/index.tsx
> +        <div style={{ marginLeft: '30vw' }}>TOPNAVBAR HERE</div>
after merging, can import top-nav-bar le.

2020-12-15 03:44 UTC, cjunxiang commented on frontend/src/routes/Profile/Components/PersonalInfoContainer.tsx
> +  font-family: Inter;
next time we will shift font-family into root style file.

2020-12-15 03:46 UTC, cjunxiang commented on frontend/src/routes/Profile/Components/PersonalInfoContainer.tsx
> +    <>
Try to style the overall container with drop shadow, border-radius etc to fit figma styling!

2020-12-15 03:47 UTC, cjunxiang requested changes
Looks cool generally! -> resolve commits -> import top nav bar -> improve styling (or just take the css code from figma) -> ask for review again!

2020-12-16 13:03 UTC, Licheng-Wu commented
Made changes according to comments, but idk how vercel deployment failed

2020-12-17 15:37 UTC, closed without merging