Replaced 'Profiles' queries with 'User' queries.
rhdevs/rhapp pull request #564
Opened 2022-01-24 05:17 UTC by porckhop

I have already tested all the changes and it all works fine. The only thing left after this is to update the 'User' validation data in MongoDB.

2022-02-01 21:26 UTC, angnobel requested changes
Generally okay, please dont return the pasword hash

2022-02-01 21:26 UTC, angnobel commented on backend/Social/SocialAPI.py
> +        data = db.User.find({"userID": {'$in': userIdList}}, {"_id": 0})
Please dont return the passwordHash for this

/profile?userID=A0223921M

2022-02-01 21:26 UTC, angnobel commented on backend/Social/SocialAPI.py
> +        data = db.User.find({"userID": userID}, {"_id": 0})
Please dont return the passwordHash for this

2022-02-01 21:26 UTC, angnobel commented on backend/Social/SocialAPI.py
> +                'from': 'User',
Please dont return the passwordHash for this

2022-02-07 05:23 UTC, porckhop commented
I have prevented passwordHash from being projected in all User queries instances. I thought this would be good, in case the code gets changed and the passwordHash is accidently projected in the future.

2022-02-09 16:32 UTC, angnobel approved these changes
Merge after reintegrate

2022-02-09 16:44 UTC, merged