Facility API Add Booking Update: bookUntil and forceBook
rhdevs/rhapp pull request #617
Opened 2022-02-28 08:08 UTC by ttheng3810

Update the POST ```/facilities/bookings/``` (```add_bookings()```) code such that 2 new JSON arguments are implemented, i.e. ```bookUntil``` and ```forceBook```.

1. ```bookUntil``` (UNIX timestamp in integers): optional argument which replaces ```repeat``` argument for the current version; when specified, new bookings are placed recurrently (spaced between a week) until any point of time within 1 week before the ```bookUntil``` timestamp.

1. ```forceBook``` (boolean value): required argument; when set as a falsy value (e.g. ```0```), the entire booking request will be rejected if there is at least one conflicting existing booking placed; when set as a truthy value (e.g. ```1```), in case of recurrent bookings, new bookings will be booked if the booking lands on an unblocked slot.

2022-03-01 13:14 UTC, angnobel requested changes
Some comments

1. If bookUntil is used, return number of bookings made
2. If there is conflict bookings now, 500 error if 'forceBook' is not provided. If not provided should default to false
3. If forceBook is true, return number of successful bookings
4. dont need remove ccaID, just add ccaName

2022-03-04 04:53 UTC, cjunxiang commented on backend/FacilityBooking/FacilitiesAPI.py
> +
wah so many empty lines
@angnobel get them to lint leh hAHAHAHH

2022-03-04 04:54 UTC, cjunxiang commented on backend/FacilityBooking/FacilitiesAPI.py
> +                    formData["endTime"] += 7 * 24 * 60 * 60
try to use global vars or abstract to helper methods to make main business logic cleaner

2022-03-06 02:57 UTC, angnobel commented
{
    "facilityID": 6,
    "eventName": "Test",
    "userID": "{{userStudentID}}",
    "startTime": 1680083200,
    "endTime": 	1680086800,
    "description": "Test",
    "ccaID": 1,
    "bookUntil": 1685083200,
    "forceBook": true
}

Causing 500 error

2022-03-11 08:37 UTC, angnobel approved these changes
LGTM

2022-03-11 08:38 UTC, merged