Finished documentation for gym
rhdevs/rhapp pull request #703
Opened 2022-09-25 19:04 UTC by yuechen2001

Finished my portion of the gym documentation for frontend  

- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in** the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

2022-10-01 12:39 UTC, gunbux submitted a review, later dismissed
It looks like there are some merge conflicts as well, the automated tests in Github is failing as well, do make sure those are passing before we can merge it!

2022-10-01 12:39 UTC, gunbux commented on .vscode/launch.json
> +    "version": "0.2.0",
Don't think this should be in the PR

2022-10-01 12:39 UTC, gunbux commented on frontend/src/components/Gym/GymKeyWith.tsx
> + *
If there's no remarks, I think you can remove this

2022-10-02 05:38 UTC, marcus-ong-qy requested changes
apologies for the late review haha; do look at them accordingly and good job!

2022-10-04 15:23 UTC, marcus-ong-qy requested changes
nice! just a few more comments

2022-10-04 15:23 UTC, marcus-ong-qy commented on frontend/src/components/Gym/GymKeyWith.tsx
> + * <GymKeyWith name={"thomaslim"} handle={"@thomas123"} avatar={""} />
btw JSX syntax string params don't need curly braces, just double quotes can alr
```suggestion
 * <GymKeyWith name="thomaslim" handle="@thomas123" avatar="" />
```

2022-10-04 15:23 UTC, marcus-ong-qy commented on frontend/src/components/Gym/GymStatus.tsx
> + * <GymStatus isOpen={True} />
another JSX syntax nitpicking haha, boolean `={true}` is redundant
```suggestion
 * <GymStatus isOpen />
```

2022-10-04 15:23 UTC, marcus-ong-qy commented on frontend/src/components/Gym/GymStatus.tsx
> + * <GymStatus isOpen={True} />
these are not wrong but just to standardise stylings around here abit; can refer to our style guides [here](https://www.notion.so/WIP-RHDevs-Frontend-Code-Style-Guide-b5f294c047f14f78b370031afb2c73c5) :)

2022-10-04 15:23 UTC, marcus-ong-qy commented on frontend/src/components/Gym/GymStatusTab.tsx
> +   * @returns a button to be displayed on the screen, with onClick function handleModalState()
```suggestion
   * @returns a button to be displayed on the screen, with onClick function handleModalState() \
```

2022-10-11 14:57 UTC, marcus-ong-qy approved these changes
make these changes then can merge alr!

2022-10-11 14:57 UTC, marcus-ong-qy commented on frontend/src/components/Gym/GymKeyWith.tsx
> + *
```suggestion
 * @example
 * ```
 * // user called Shaun and has no profile picture
 * // component will display the default profile picture, his name Shaun as well as his
 * // telegram handle. Clicking on the telegram handle redirects the user to key holder's telegram
 * <GymKeyWith name="thomaslim" handle="@thomas123" avatar="" />
 * ```
 *
```

2022-10-11 14:57 UTC, marcus-ong-qy commented on frontend/src/components/Gym/GymStatus.tsx
> + * <GymStatus isOpen />
```suggestion
 * @example
 * ```
 * // Retrieves gym status from backend. If the gym is closed, display "Gym is Closed" in red
 * <GymStatus isOpen />
 * ```
```

2022-10-11 15:09 UTC, merged